export const ApparelTypesInfos = {
    // active: 'activewear',
    athletic: 'athletic shoes',
    'button-down': 'button-down',
    bath: 'bath towel',
    blazer: 'blazer',
    blouse: 'blouse',
    boot: 'boots',
    boxer: 'boxers',
    bra: 'bra',
    cami: 'camisole',
    cap: 'baseball-cap',
    cargo: 'cargo pants',
    casual: 'casual pants',
    chinos: 'chinos',
    dress: 'dress',
    'f/f': 'flip-flop',
    flannel: 'flannel',
    fleece: 'fleece jacket',
    glove: 'gloves',
    graphic: 'graphic-tee',
    'h/h': 'high-heel',
    hand: 'hand towel',
    hat: 'hat',
    hoodie: 'hoodie',
    jacket: 'jacket',
    jeans: 'jeans',
    khaki: 'khakis',
    leggings: 'leggings',
    loafer: 'loafers',
    'denim-shorts': 'denim shorts',
    mitten: 'mittens',
    neg: 'negligee',
    'o/a': 'overalls',
    oxford: 'oxford shirt',
    'p/o': 'pull-over',
    pj: 'pajamas',
    'pj-b': 'pajama-bottom',
    'pj-t': 'pajama-top',
    polo: 'polo',
    sandal: 'sandals',
    scarf: 'scarf',
    'short-shorts': 'short shorts',
    shorts: 'shorts',
    skirt: 'skirt',
    shirt: 'shirt',
    sleep: 'sleepwear',
    sneaker: 'sneakers',
    sock: 'socks',
    stiletto: 'stilletos',
    suit: 'suit',
    sweat: 'sweatshirt',
    't/t': 'tank-top',
    tee: 'tee-shirt',
    tie: 'tie',
    towel: 'towel',
    trench: 'trenchcoat',
    trouser: 'trousers',
    tube: 'tube-top',
    'u/w': 'underwear',
    'w/c': 'wash cloth',
    wind: 'windbreaker',
    'wash-cloth': 'wash-cloth',
    underwear: 'underwear',
    'tank-top': 'tank-top',
    'pull-over': 'pull-over',
    'over-alls': 'over-alls',
    'high-heel': 'high-heel',
    'flip-flop': 'flip-flop',
    lingerie: 'lingerie'
};

export type ApparelTypesKeys = keyof typeof ApparelTypesInfos;