export const { family, order, genus } = {
    family: {
        accessories: 'accessories',
        shoes: 'shoes',
        tops: 'tops',
        bottoms: 'bottoms',
        undergarments: 'undergarments',
        sleepwear: 'sleepwear',
        fullbody: 'fullbody'
    },
    order: {
        mid: 'mid',
        head: 'head',
        hands: 'hands',
        heeled: 'heeled',
        flats: 'flats',
        sneakers: 'sneakers',
        boots: 'boots',
        shirts: 'shirts',
        jackets: 'jackets',
        'button-front': 'button-front',
        sweaters: 'sweaters',
        other: 'other',
        'full-length': 'full-length',
        shorts: 'shorts',
        jeans: 'jeans',
        socks: 'socks',
        mens: 'mens',
        womens: 'womens',
        lingerie: 'lingerie',
        pajamas: 'pajamas',
        robes: 'robes',
        dresses: 'dresses',
        suits: 'suits',
        overalls: 'overalls'
    },
    genus: {
        tie: 'tie',
        belt: 'belt',
        cumberbund: 'cumberbund',
        suspenders: 'suspenders',
        wallet: 'wallet',
        baseball: 'baseball',
        cowboy: 'cowboy',
        fedora: 'fedora',
        skull: 'skull',
        sunglasses: 'sunglasses',
        visor: 'visor',
        gloves: 'gloves',
        mittens: 'mittens',
        work: 'work',
        watch: 'watch',
        'high-heel': 'high-heel',
        stiletto: 'stiletto',
        wedge: 'wedge',
        sandal: 'sandal',
        loafer: 'loafer',
        'flip-flop': 'flip-flop',
        athletic: 'athletic',
        skate: 'skate',
        'high-top': 'high-top',
        runners: 'runners',
        basketball: 'basketball',
        hiking: 'hiking',
        't-shirt': 't-shirt',
        camisole: 'camisole',
        'tank-top': 'tank-top',
        'tube-top': 'tube-top',
        halter: 'halter',
        sleeveless: 'sleeveless',
        wrap: 'wrap',
        tunic: 'tunic',
        fleece: 'fleece',
        bomber: 'bomber',
        leather: 'leather',
        windbreaker: 'windbreaker',
        trenchcoat: 'trenchcoat',
        raincoat: 'raincoat',
        denim: 'denim',
        hoodie: 'hoodie',
        overcoat: 'overcoat',
        poncho: 'poncho',
        polo: 'polo',
        rugby: 'rugby',
        oxford: 'oxford',
        'button-down': 'button-down',
        fitted: 'fitted',
        flannel: 'flannel',
        henley: 'henley',
        hawaiian: 'hawaiian',
        blouse: 'blouse',
        'dress-shirt': 'dress-shirt',
        sweater: 'sweater',
        sweatshirt: 'sweatshirt',
        'pull-over': 'pull-over',
        tutleneck: 'tutleneck',
        cardigan: 'cardigan',
        carpenter: 'carpenter',
        cargo: 'cargo',
        chinos: 'chinos',
        khakis: 'khakis',
        pleated: 'pleated',
        casual: 'casual',
        corduroys: 'corduroys',
        trousers: 'trousers',
        DEFAULT: 'DEFAULT',
        short: 'short',
        board: 'board',
        bermuda: 'bermuda',
        khaki: 'khaki',
        bike: 'bike',
        surf: 'surf',
        gym: 'gym',
        relaxed: 'relaxed',
        boot: 'boot',
        slim: 'slim',
        skinny: 'skinny',
        baggy: 'baggy',
        flare: 'flare',
        'slim-boot': 'slim-boot',
        'bell-bottom': 'bell-bottom',
        straight: 'straight',
        'cropped-pants': 'cropped-pants',
        skort: 'skort',
        capris: 'capris',
        'track-pants': 'track-pants',
        leggings: 'leggings',
        tights: 'tights',
        sweatpants: 'sweatpants',
        skirt: 'skirt',
        mid: 'mid',
        crew: 'crew',
        ankle: 'ankle',
        'knee-high': 'knee-high',
        briefs: 'briefs',
        boxers: 'boxers',
        jock: 'jock',
        bra: 'bra',
        panties: 'panties',
        stockings: 'stockings',
        'panty-hose': 'panty-hose',
        negligee: 'negligee',
        top: 'top',
        bottom: 'bottom',
        set: 'set',
        robe: 'robe',
        nightgown: 'nightgown',
        tuxedo: 'tuxedo',
        'double-breasted': 'double-breasted',
        '1-button': '1-button',
        '2-button': '2-button',
        '3-button': '3-button',
        '4-button': '4-button',
        bodysuit: 'bodysuit',
        'pant-suit': 'pant-suit',
        jumpsuit: 'jumpsuit',
        romper: 'romper'
    }
};

    
export const ApparelFamilies = family;
export type ApparelFamilies = typeof ApparelFamilies;
export type ApparelFamiliesKey = keyof ApparelFamilies;

export const ApparelOrders = order;
export type ApparelOrders = typeof ApparelOrders;
export type ApparelOrdersKey = keyof ApparelOrders;

export const ApparelGenuses = genus;
export type ApparelGenuses = typeof ApparelGenuses;
export type ApparelGenusesKey = keyof ApparelGenuses;