export type SleeveTypes = {
    batwing: string;
    bell: string;
    bishop: string;
    bracelet: string;
    butterfly: string;
    button: string;
    cape: string;
    circular: string;
    cowl: string;
    drop: string;
    french: string;
    juliet: string;
    kimono: string;
    lantern: string;
    layer: string;
    less: string;
    long: string;
    marie: string;
    mutton: string;
    off: string;
    peasant: string;
    petal: string;
    poet: string;
    puffed: string;
    raglan: string;
    rollup: string;
    shirt: string;
    short: string;
    quarter: string;
};
export type SleeveTypesKey = keyof SleeveTypes;
export const SleeveTypes: EnumMap<SleeveTypesKey> = {
    batwing: 'batwing',
    bell: 'bell',
    bishop: 'bishop',
    bracelet: 'bracelet',
    butterfly: 'butterfly',
    button: 'button-tab',
    cape: 'cape',
    circular: 'circular-cap',
    cowl: 'cowl',
    drop: 'drop-shoulder',
    french: 'french',
    juliet: 'juliet',
    kimono: 'kimono',
    lantern: 'lantern',
    layer: 'layered',
    less: 'sleeveless',
    long: 'long-sleeved',
    marie: 'marie',
    mutton: 'leg-of-mutton',
    off: 'off-shoulder',
    peasant: 'peasant',
    petal: 'petal',
    poet: 'poet',
    puffed: 'puffed',
    raglan: 'raglan',
    rollup: 'roll-up',
    shirt: 'cuffed',
    short: 'short-sleeved',
    quarter: '3/4-sleeve'
};
